export const buttonList = [
  { class: "operator", value: "+" },
  { class: "operator", value: "-" },
  { class: "operator", value: "*" },
  { class: "operator", value: "/" },
  { value: "7" },
  { value: "8" },
  { value: "9" },
  { value: "4" },
  { value: "5" },
  { value: "6" },
  { value: "1" },
  { value: "2" },
  { value: "3" },
  { class: "all-clear", value: "AC" },
  { value: "0" },
  { class: "decimal", value: "." },
  { class: "equal-sign", value: "=" },
];